name = "Inari Sami"
version = "1.0.5"

[macos]
system_pkg_id = "no.divvun.MacDivvun.smn"

[windows]
system_product_code = "{6C8F8631-3603-4071-BCB1-D241A3978FBF}_is1"
legacy_product_codes = [
    { value = "BEDA0EAE-9336-5420-84F8-2F6967808426", kind = "nsis" },
    { value = "CD5F291A-50B8-40E2-A791-D9C3F7256FD1", kind = "nsis" },
]
extra_locales = { smn-FI = "smn" }
