theme: jekyll-theme-minimal
title: Inari SÃ¡mi NLP Grammar
description: Finite state and Constraint Grammar based analysers, proofing tools and other resources
plugins:
  - jemoji
  - jekyll-include-cache

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
